# ==============================================================
# Eliot Camp Information
# ==============================================================

[camps]
july    = "July Eliot"
august  = "August Eliot"
cae     = "Creative Arts Eliot"
winter  = "Winter Eliot"

# years with camp data to display
years = [
  2026,
  2025,
  2024
]

# ==============================================================
# Camp data example
# ==============================================================

# [2026.cae]                  // Year and camp name
# speaker = "Speaker's Name"  // [optional] Speaker
# topic   = "Topic"           // Topic
# start   = 2026-08-08        // Start date
# end     = 2026-08-12        // End date
# hide    = true              // [optional] hide camp if true
# md      = true              // [optional] set to true if file
#                                 exists (e.g 2026/cae.md)

# ==============================================================

