# ==============================================================
# Eliot Camp Information
#
# names: displayed name for each camp (year will be appended)
# ==============================================================

[names]
july    = "July Eliot"
august  = "August Eliot"
cae     = "Creative Arts Eliot"
winter  = "Winter Eliot"

# ==============================================================
# Camp data example
# ==============================================================

# [2026.cae]                  // Year and camp name
# speaker = "Speaker's Name"  // [optional] Speaker
# topic   = "Topic"           // Topic
# start   = 2026-08-08        // Start date
# end     = 2026-08-12        // End date
# md      = true              // [optional] set to true if file
#                                 exists (e.g 2026/cae.md)

# ==============================================================

# ==============================================================
# 2026
# ==============================================================

[2026.cae]
topic   = "Your Choice of Workshops"
start   = 2026-08-08
end     = 2026-08-12
md      = true

[2026.august]
speaker = "Will Hornyak"
topic   = "Sheherazade's Caravan"
start   = 2026-08-01
end     = 2026-08-08
md      = true

[2026.july]
speaker = "Zr. Alex Kapitan"
topic   = "Exploring and Celebrating Gender Diversity, Trans Justice, and Faith"
start   = 2026-07-11
end     = 2026-07-18
md      = true

# ==============================================================
# 2025
# ==============================================================

[2025.winter]
speaker = "Melanie DeMore"
topic   = "Stick Pounding"
start   = 2025-12-28
end     = 2026-12-01
md      = true

[2025.cae]
topic   = "Creative Arts Eliot"
start   = 2025-08-09
end     = 2025-08-13
md      = false

[2025.august]
speaker = "Guy Nelson"
topic   = "Creativity Games & Storytelling"
start   = 2025-08-02
end     = 2025-08-09
md      = false

[2025.july]
speaker = "Lea Morris"
topic   = "Joyful Noise: Sing Out, Be Free"
start   = 2025-07-11
end     = 2025-07-18
md      = false

# ==============================================================
# 2024
# ==============================================================
[2024.winter]
speaker = "Elin Kelsey"
topic   = "The Practice of Evidence-Based Hope"
start   = 2024-12-28
end     = 2024-12-01
