# ==============================================================
# 2025 Camps
# ==============================================================

[july]
speaker = "Lea Morris"
topic   = "Joyful Noise: Sing Out, Be Free"
start   = 2025-07-11
end     = 2025-07-18
md      = false

[august]
speaker = "Guy Nelson"
topic   = "Creativity Games & Storytelling"
start   = 2025-08-02
end     = 2025-08-09
md      = false

[cae]
topic   = "Creative Arts Eliot"
start   = 2025-08-09
end     = 2025-08-13
md      = false

[winter]
speaker = "Melanie DeMore"
topic   = "Stick Pounding"
start   = 2025-12-28
end     = 2026-12-01
md      = true
