# ==============================================================
# 2026
# ==============================================================

[2026.july]
speaker = "Zr. Alex Kapitan"
topic   = "Exploring and Celebrating Gender Diversity, Trans Justice, and Faith"
start   = 2026-07-11
end     = 2026-07-18
md      = true

[2026.august]
speaker = "Will Hornyak"
topic   = "Sheherazade's Caravan"
start   = 2026-08-01
end     = 2026-08-08
md      = true

[2026.cae]
topic   = "Your Choice of Workshops"
start   = 2026-08-08
end     = 2026-08-12
md      = true

[winter]
speaker = "TBD"
topic   = "TBD"
start   = 2026-12-28
end     = 2027-12-01
md      = false
hide    = true
